/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package consumer;

public class ElasticsearchConsumer {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new ElasticsearchConsumer().getGreeting());
    }
}
